permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: 小为
  email: xiaxiaowei@outlook.com
  link: http://xiaxiaowei.github.io
  weibo:
  github: http://github.com/xiaxiaowei

# 站点信息
title: 小为的博客
description: 小为的博客
url: http://xiaxiaowei.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: http://7u2pqg.com1.z0.glb.clouddn.com/blog_header.jpg
favicon: http://7u2pqg.com1.z0.glb.clouddn.com/blog_header.jpg

# google analytics 设置
ga:
  id:
  url:

# disqus 设置
disqus:
  shortname:

# 主题设置，自动激活某个标签
active: iOS

# 首页除了最新文章外显示分类
cates: 
  - iOS
  - Python

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
